version:"3"
service:
	test_database:
		image: mysql:5.7
		enviroment:
			MYSQL_DATABASE: test_db
			MYSQL_ROOT_PASSWORD: root
			MYSQL_ROOT_HOST:'%'
		ports:
			- 3306:3306

	test_application:
		build: .
		ports:
			- 8080:8080
		depends_on:
			- test_database
