version: "3"

services:
	test_application:
		images: openjdk:8u212-jdk
		container_name: "test_application"
		command: "java -jar /usr/src/myapp/SpringBootSample-0.0.1.jar"
		volumes:
			- /inteliJ/testapp/build/libs:/usr/src/myapp
		ports:
			- 8080:8080
