version: "3"

services:
    test_database:
        container_name: mysql
        image: mysql:latest
        environment:
            MYSQL_DATABASE: testdb
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_HOST: '%'
        ports:
          - 3307:3307

    test_application:
        container_name: "test_application"
        build: .
        environment:
            MYSQL_ADDRESS: test_database
            MYSQL_USERNAME: root
            MYSQL_PASSWORD: root
        ports:
            - 8080:8080
        links:
          - test_database
        depends_on:
          - test_database
